// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: producer.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EventService.Protocol {
  public static partial class ProducerService
  {
    static readonly string __ServiceName = "protocol.ProducerService";

    static readonly grpc::Marshaller<global::EventService.Protocol.ProducerRequest> __Marshaller_protocol_ProducerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EventService.Protocol.ProducerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EventService.Protocol.ProducerResponse> __Marshaller_protocol_ProducerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EventService.Protocol.ProducerResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::EventService.Protocol.ProducerRequest, global::EventService.Protocol.ProducerResponse> __Method_Connect = new grpc::Method<global::EventService.Protocol.ProducerRequest, global::EventService.Protocol.ProducerResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Connect",
        __Marshaller_protocol_ProducerRequest,
        __Marshaller_protocol_ProducerResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EventService.Protocol.ProducerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProducerService</summary>
    public abstract partial class ProducerServiceBase
    {
      public virtual global::System.Threading.Tasks.Task Connect(grpc::IAsyncStreamReader<global::EventService.Protocol.ProducerRequest> requestStream, grpc::IServerStreamWriter<global::EventService.Protocol.ProducerResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProducerService</summary>
    public partial class ProducerServiceClient : grpc::ClientBase<ProducerServiceClient>
    {
      /// <summary>Creates a new client for ProducerService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ProducerServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProducerService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ProducerServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ProducerServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ProducerServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::EventService.Protocol.ProducerRequest, global::EventService.Protocol.ProducerResponse> Connect(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::EventService.Protocol.ProducerRequest, global::EventService.Protocol.ProducerResponse> Connect(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Connect, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ProducerServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProducerServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ProducerServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Connect, serviceImpl.Connect).Build();
    }

  }
}
#endregion
